### ISSUE TITLE
Reward values differ between video plugins

### ISSUE THREAD

**Issue by bzier** [bzier/gym-mupen64plus#91]
I discovered that I can actually run both Glide64 and Glide64mk2. It appears that specifying a plugin name will attempt to match a plugin by name. Specifying `mupen64plus-video-glide64` was matching `mupen64plus-video-glide64mk2.so`. If I specify the 'full' name as `mupen64plus-video-glide64.so` with the `.so` extension, it properly loads Glide64. Here are the current reward values for the two hard-coded races I have at the moment:
```yml
"Luigi Raceway"
      Rice: 3807.3
Glide64mk2: 3807.9
   Glide64: 3588.3

"Mario Raceway"
      Rice: 4390.8
Glide64mk2: 4390.2
   Glide64: 4213.2
```
Still need to look into the discrepancy in the values. Why do they differ when the action sequence and progression through the race is the same?

_Originally posted by @bzier in https://github.com/bzier/gym-mupen64plus/issues/53#issuecomment-388582061_
